pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/davidmartinez-esc/ev1_TingesoFrontend']])
                dir("ev1_frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("ev1_frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t dddavidesc/imagen-frontend-web ."
                            bat "docker push dddavidesc/imagen-frontend-web"
                        }
                    }                    
                }
            }
        }
    }
}
